
# SERVER CONFIGURATION

server.port=8080


# ORACLE DATASOURCE

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=ARIESONE188_SCHEMA_UQ4ZA
spring.datasource.password=EEEXX1FJ3E3NUACIWOU9LC6!MNnLYT
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect


# LOGGING

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
